### ISSUE TITLE
brew install --HAED david-icracked/websocketpp/websocketpp(OSX)

### ISSUE THREAD

**Issue by rideoff** [davidp-icracked/homebrew-websocketpp#1]
==> Installing websocketpp from david-icracked/websocketpp
==> Cloning git://github.com/zaphoyd/websocketpp
Updating /Users/lanjiedediannao/Library/Caches/Homebrew/websocketpp--git
==> Checking out branch master
==> cmake  . ["-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_CXX_FLAGS_RELEASE=-DN
Last 15 lines from /Users/lanjiedediannao/Library/Logs/Homebrew/websocketpp/01.HEAD-378437a",:
2018-05-24 17:46:08 +0800

cmake  . ["-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG", "-DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/websocketpp/HEAD-378437a", "-DCMAKE_BUILD_TYPE=Release", "-DCMAKE_FIND_FRAMEWORK=LAST", "-DCMAKE_VERBOSE_MAKEFILE=ON", "-Wno-dev"]

CMake Error: The source directory "/tmp/websocketpp-20180524-1500-hrqv7h/[-DCMAKE_C_FLAGS_RELEASE=-DNDEBUG," does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/david-icracked/homebrew-websocketpp/issues

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:220:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:178:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:292:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:225:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:238:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:368:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:364:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:418:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:25:in `<main>'

**Comment by lindsaymorgan** [comment]
I also met this problem, any updates?
